### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by marcelo-pereira-pcst** [ppnasser/pnadc#1]
I'm having a UnicodeDecodeError when trying to run the get method. The exact error log is as follows

`
  File "/home/marcelo/anaconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 67: invalid continuation byte`

My OS is Ubuntu 20.04 and I'm running the code on Spyder (Python 3.7) in a Anaconda environment.

**Comment by ppnasser** [comment]
Hi @tbmpereira , thanks for submitting this issue!
Could you please share a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example) that outputs your problem? Also if possible a printscreen of the ipython prompt in spyder (so we can see at which step it crashed)?

**Comment by marcelo-pereira-pcst** [comment]
code would be as simple as

`import pnadc

pnadc.get(2, 2019)`

check the printscreen of the log error
![erro_pnadc](https://user-images.githubusercontent.com/53980193/95593781-7f8b5100-0a20-11eb-9d4b-f6e51aae3bd1.png)
 attached as well

**Comment by ppnasser** [comment]
@tbmpereira I found out that the dictionary must be opened using latin-1 for Linux users. Fixed and updated the package to v0.0.4. It worked on Debian, please reinstall and see if it works for you too.

**Comment by marcelo-pereira-pcst** [comment]
I updated the module. It's not raising the UnicodeDecodeError anymore, but now the kernel is dying while trying to build the DataFrame.

**Comment by ppnasser** [comment]
Well, this is unexpected... are u using a Virtual Machine to run Ubuntu? It could be a lack of RAM... I will incorporate Dask in near futher releases, which will require less memory and processing time.
